apiVersion: v1
kind: Service
metadata:
    name: nginx
    namespace: imad-system
    labels:
        app: nginx
spec:
    type: NodePort
    ports:
    -   port: 30080
        targetPort: 80 
        name: http    
        nodePort: 30080
    selector:
        app: nginx
