apiVersion: v1
kind: Service
metadata:
    name: nginx
    namespace: imad-system
    labels:
        app: nginx
spec:
    type: LoadBalancer
    ports:
    -   port: 80
        targetPort: 80 
        name: http    
    selector:
        app: nginx
